USE [master]
GO

/****** Object:  Database [WebShop]    Script Date: 15.4.2019. 16:37:51 ******/
CREATE DATABASE [WebShop]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WebShop', FILENAME = N'C:\Users\programer\Code\MVC2019\WebShop\App_Data\WebShop.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'WebShop_log', FILENAME = N'C:\Users\programer\Code\MVC2019\WebShop\App_Data\WebShop_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [WebShop] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WebShop].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WebShop] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WebShop] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WebShop] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WebShop] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WebShop] SET ARITHABORT OFF 
GO

ALTER DATABASE [WebShop] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WebShop] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WebShop] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WebShop] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WebShop] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WebShop] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WebShop] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WebShop] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WebShop] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WebShop] SET  DISABLE_BROKER 
GO

ALTER DATABASE [WebShop] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WebShop] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WebShop] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WebShop] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WebShop] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WebShop] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WebShop] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WebShop] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [WebShop] SET  MULTI_USER 
GO

ALTER DATABASE [WebShop] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WebShop] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WebShop] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [WebShop] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [WebShop] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [WebShop] SET QUERY_STORE = OFF
GO

USE [WebShop]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [WebShop] SET  READ_WRITE 
GO

